/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitsRouteImport } from './routes/visits'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RightsRouteImport } from './routes/rights'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OwnersRouteImport } from './routes/owners'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as OwnersRegisterRouteImport } from './routes/owners.register'
import { Route as LegalTenantIdRouteImport } from './routes/legal.$tenantId'
import { Route as DashboardTenantRouteImport } from './routes/dashboard.tenant'
import { Route as DashboardOwnerRouteImport } from './routes/dashboard.owner'
import { Route as DashboardAgentRouteImport } from './routes/dashboard.agent'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as ApplyPropertyIdRouteImport } from './routes/apply.$propertyId'

const VisitsRoute = VisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RightsRoute = RightsRouteImport.update({
  id: '/rights',
  path: '/rights',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnersRoute = OwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PropertiesRoute,
} as any)
const OwnersRegisterRoute = OwnersRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => OwnersRoute,
} as any)
const LegalTenantIdRoute = LegalTenantIdRouteImport.update({
  id: '/legal/$tenantId',
  path: '/legal/$tenantId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTenantRoute = DashboardTenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOwnerRoute = DashboardOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentRoute = DashboardAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const ApplyPropertyIdRoute = ApplyPropertyIdRouteImport.update({
  id: '/apply/$propertyId',
  path: '/apply/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/owners': typeof OwnersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/register': typeof RegisterRoute
  '/rights': typeof RightsRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/visits': typeof VisitsRoute
  '/apply/$propertyId': typeof ApplyPropertyIdRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/agent': typeof DashboardAgentRoute
  '/dashboard/owner': typeof DashboardOwnerRoute
  '/dashboard/tenant': typeof DashboardTenantRoute
  '/legal/$tenantId': typeof LegalTenantIdRoute
  '/owners/register': typeof OwnersRegisterRoute
  '/properties/$id': typeof PropertiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/owners': typeof OwnersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/register': typeof RegisterRoute
  '/rights': typeof RightsRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/visits': typeof VisitsRoute
  '/apply/$propertyId': typeof ApplyPropertyIdRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/agent': typeof DashboardAgentRoute
  '/dashboard/owner': typeof DashboardOwnerRoute
  '/dashboard/tenant': typeof DashboardTenantRoute
  '/legal/$tenantId': typeof LegalTenantIdRoute
  '/owners/register': typeof OwnersRegisterRoute
  '/properties/$id': typeof PropertiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/owners': typeof OwnersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/register': typeof RegisterRoute
  '/rights': typeof RightsRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/visits': typeof VisitsRoute
  '/apply/$propertyId': typeof ApplyPropertyIdRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/agent': typeof DashboardAgentRoute
  '/dashboard/owner': typeof DashboardOwnerRoute
  '/dashboard/tenant': typeof DashboardTenantRoute
  '/legal/$tenantId': typeof LegalTenantIdRoute
  '/owners/register': typeof OwnersRegisterRoute
  '/properties/$id': typeof PropertiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/login'
    | '/notifications'
    | '/owners'
    | '/privacy'
    | '/profile'
    | '/properties'
    | '/register'
    | '/rights'
    | '/services'
    | '/terms'
    | '/visits'
    | '/apply/$propertyId'
    | '/dashboard/admin'
    | '/dashboard/agent'
    | '/dashboard/owner'
    | '/dashboard/tenant'
    | '/legal/$tenantId'
    | '/owners/register'
    | '/properties/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/login'
    | '/notifications'
    | '/owners'
    | '/privacy'
    | '/profile'
    | '/properties'
    | '/register'
    | '/rights'
    | '/services'
    | '/terms'
    | '/visits'
    | '/apply/$propertyId'
    | '/dashboard/admin'
    | '/dashboard/agent'
    | '/dashboard/owner'
    | '/dashboard/tenant'
    | '/legal/$tenantId'
    | '/owners/register'
    | '/properties/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/login'
    | '/notifications'
    | '/owners'
    | '/privacy'
    | '/profile'
    | '/properties'
    | '/register'
    | '/rights'
    | '/services'
    | '/terms'
    | '/visits'
    | '/apply/$propertyId'
    | '/dashboard/admin'
    | '/dashboard/agent'
    | '/dashboard/owner'
    | '/dashboard/tenant'
    | '/legal/$tenantId'
    | '/owners/register'
    | '/properties/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OwnersRoute: typeof OwnersRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  RightsRoute: typeof RightsRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  VisitsRoute: typeof VisitsRoute
  ApplyPropertyIdRoute: typeof ApplyPropertyIdRoute
  LegalTenantIdRoute: typeof LegalTenantIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visits': {
      id: '/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof VisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rights': {
      id: '/rights'
      path: '/rights'
      fullPath: '/rights'
      preLoaderRoute: typeof RightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owners': {
      id: '/owners'
      path: '/owners'
      fullPath: '/owners'
      preLoaderRoute: typeof OwnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/owners/register': {
      id: '/owners/register'
      path: '/register'
      fullPath: '/owners/register'
      preLoaderRoute: typeof OwnersRegisterRouteImport
      parentRoute: typeof OwnersRoute
    }
    '/legal/$tenantId': {
      id: '/legal/$tenantId'
      path: '/legal/$tenantId'
      fullPath: '/legal/$tenantId'
      preLoaderRoute: typeof LegalTenantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tenant': {
      id: '/dashboard/tenant'
      path: '/tenant'
      fullPath: '/dashboard/tenant'
      preLoaderRoute: typeof DashboardTenantRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/owner': {
      id: '/dashboard/owner'
      path: '/owner'
      fullPath: '/dashboard/owner'
      preLoaderRoute: typeof DashboardOwnerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agent': {
      id: '/dashboard/agent'
      path: '/agent'
      fullPath: '/dashboard/agent'
      preLoaderRoute: typeof DashboardAgentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/apply/$propertyId': {
      id: '/apply/$propertyId'
      path: '/apply/$propertyId'
      fullPath: '/apply/$propertyId'
      preLoaderRoute: typeof ApplyPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAgentRoute: typeof DashboardAgentRoute
  DashboardOwnerRoute: typeof DashboardOwnerRoute
  DashboardTenantRoute: typeof DashboardTenantRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAgentRoute: DashboardAgentRoute,
  DashboardOwnerRoute: DashboardOwnerRoute,
  DashboardTenantRoute: DashboardTenantRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface OwnersRouteChildren {
  OwnersRegisterRoute: typeof OwnersRegisterRoute
}

const OwnersRouteChildren: OwnersRouteChildren = {
  OwnersRegisterRoute: OwnersRegisterRoute,
}

const OwnersRouteWithChildren =
  OwnersRoute._addFileChildren(OwnersRouteChildren)

interface PropertiesRouteChildren {
  PropertiesIdRoute: typeof PropertiesIdRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesIdRoute: PropertiesIdRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OwnersRoute: OwnersRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
  RegisterRoute: RegisterRoute,
  RightsRoute: RightsRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  VisitsRoute: VisitsRoute,
  ApplyPropertyIdRoute: ApplyPropertyIdRoute,
  LegalTenantIdRoute: LegalTenantIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
